# permissions for end users to view wholepics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wholepic-viewer-role
rules:
- apiGroups:
  - webapp.liangbin.xyz
  resources:
  - wholepics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.liangbin.xyz
  resources:
  - wholepics/status
  verbs:
  - get
